language: python
python:
- "3.6"

#safelist
branches:
  only:
    - dev

install:
  - pip3 install -r requirements-test.txt
  - ansible-galaxy collection install requirements.yml
  - ansible-galaxy role install requirements.yml
script:
  - ansible-lint *.yml