language: python
python:
  - "3.6"

# safelist
branches:
  only:
    - dev

install:
  - pip3 install -r requirements-test.txt
  - ansible-galaxy collection install -r requirements.yml
  - ansible-galaxy role install -r requirements.yml
script:
  - ansible-lint backup-all.yml
